#include "rev_a.h"
/* PROTOTYPE_TUNING_REQUIRED. No waveform or physical limit has been verified. */
const fw_config_t rev_a_config = {.pwm_hz = 200000u,
                                  .adc_phase_ticks = 6800u,
                                  .deadtime_ticks = 34u,
                                  .bus_min = 22.0f,
                                  .bus_max = 26.0f,
                                  .cap_min = 12.0f,
                                  .cap_max = 22.05f,
                                  .cap_limit_a = 9.5f,
                                  .il_limit_a = 9.5f,
                                  .fast_trip_a = 11.0f,
                                  .charge_w = 40.0f,
                                  .assist_w = 80.0f,
                                  .peak_w = 120.0f,
                                  .efficiency = 0.90f,
                                  .temp_warn = {60.0f, 60.0f, 45.0f},
                                  .temp_stop = {65.0f, 65.0f, 50.0f},
                                  .temp_rearm = {50.0f, 50.0f, 40.0f},
                                  .can_timeout_ms = 250u,
                                  .sensor_timeout_ms = 50u,
                                  .precharge_ms = 3000u,
                                  .peak_ms = 1000u,
                                  .repetition_ms = 30000u,
                                  .settle_ms = 100u,
                                  .balance_settle_ms = 250u,
                                  .discharge_timeout_ms = 2400000u,
                                  .tuning_verified = false,
                                  .commissioning_authorized = false,
                                  .service_dump_authorized = false};
